[workspace]
members = [
    "legacy",
    "day_1/fib",
    "day_1/collatz",
    "day_1/nested_arrays",
    "day_1/geometry",
    "day_2/expr_eval",
    "day_2/gui_library",
    "day_2/generic_min",
    "day_3/builder_type",
    "day_4/luhn",
]
resolver = "2"
